"""rename department

Revision ID: 9e5ed9ecc0d2
Revises: 70c17ee808a9
Create Date: 2025-02-11 15:47:45.218719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5ed9ecc0d2'
down_revision = '70c17ee808a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
